version: "3.7"
services:
    bootstrap-py:
        volumes:
            - ./app:/app
        build: .
        ports:
            - "5656:5656"
        image: local/bootstrap-py
        command:  python do.py
    redis:
        ports:
            - 6379:6379
        image: redislabs/rejson:latest
